# Generated by Django 2.1.7 on 2019-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190310_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytm_history',
            name='TXNID',
            field=models.CharField(max_length=100, verbose_name='TXN ID'),
        ),
    ]
