# Generated by Django 2.1.7 on 2019-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190310_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytm_history',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BANK TXN ID'),
        ),
    ]
