# Generated by Django 2.1.7 on 2019-03-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='trans_id',
            field=models.TextField(blank=True),
        ),
    ]
