# Generated by Django 2.1.7 on 2019-03-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190305_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='team_count',
            field=models.IntegerField(default=1),
        ),
    ]
