# Generated by Django 2.1.7 on 2019-03-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190305_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='user_details',
            name='contact_no',
            field=models.IntegerField(default=91),
        ),
    ]
